version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis:6379
    volumes:
      - .:/app
    depends_on:
      - redis
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass $REDIS_PASSWORD --appendonly yes
